# Generated by Django 4.2.2 on 2023-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='project_logos/')),
                ('status_icon', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('acquired_date', models.DateField()),
            ],
        ),
    ]
