# Generated by Django 4.2.2 on 2023-07-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0002_alter_project_status_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='acquired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
