# Generated by Django 4.2.2 on 2023-07-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0011_remove_milestone_date_range_milestone_end_date_and_more'),
    ]

    operations = [
    ]
