# Generated by Django 4.2.2 on 2023-07-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0012_auto_20230720_1143'),
    ]

    operations = [
    ]
