# Generated by Django 4.2.2 on 2023-07-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0014_auto_20230720_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
