# Generated by Django 4.2.2 on 2023-07-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0017_alter_milestone_end_date_alter_milestone_start_date'),
    ]

    operations = [
    ]
