# Generated by Django 4.2.2 on 2023-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0019_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='profile_photo',
            field=models.ImageField(blank=True, default='review_images/default_user.png', null=True, upload_to='review_images'),
        ),
    ]
