# Generated by Django 4.2.2 on 2023-07-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0021_remove_project_acquired_date_project_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='acquired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
