# Generated by Django 4.2.2 on 2023-08-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0022_project_acquired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.CharField(default='John Kibocha', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
