# Generated by Django 4.2.2 on 2023-08-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0023_project_background_image_project_developers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='background_image',
        ),
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.PositiveIntegerField(default=20000),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.URLField(default='https://github.com'),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(default='https://johnkibocha.com'),
        ),
    ]
