# Generated by Django 4.2.2 on 2023-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0025_alter_project_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
