# Generated by Django 4.2.2 on 2023-08-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0027_alter_project_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
