# Generated by Django 3.2.21 on 2023-10-16 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0029_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='profile_images/john_kibocha_profile.jpeg', null=True, upload_to='profile_images')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Request Source Code', 'Request Source Code'), ('Reach Out', 'Reach Out'), ('Request Resume', 'Request Resume'), ('Collaborate', 'Collaborate'), ('Chat', 'Chat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='projects',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tools',
            field=models.CharField(default='Python', max_length=200),
        ),
    ]
