# Generated by Django 3.2.21 on 2023-11-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0030_auto_20231016_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='company_name',
            new_name='what_do_you_do',
        ),
        migrations.RemoveField(
            model_name='review',
            name='company_position',
        ),
        migrations.AddField(
            model_name='review',
            name='where_do_you_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
