# Generated by Django 3.2.21 on 2023-11-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0031_auto_20231109_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(help_text='John Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='profile_photo',
            field=models.ImageField(blank=True, default='review_images/default_user.png', help_text='Optional', null=True, upload_to='review_images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='what_do_you_do',
            field=models.CharField(help_text='Software Engineer', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='where_do_you_work',
            field=models.CharField(blank=True, help_text='Google Inc. (optional)', max_length=100, null=True),
        ),
    ]
