# Generated by Django 3.2.21 on 2023-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0032_auto_20231109_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='profile_photo',
            field=models.ImageField(blank=True, default='review_images/default_user.png', help_text='(Optional)', null=True, upload_to='review_images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='what_do_you_do',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='where_do_you_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
