# Generated by Django 3.2.21 on 2023-11-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_kibocha_app', '0033_auto_20231109_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='profile_images/john_kibocha_profile.jpeg', null=True, upload_to='profile_images')),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('favorite_programming_languages', models.CharField(max_length=100)),
                ('additional_information', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
    ]
